# Generated by Django 3.2.7 on 2021-11-19 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('company_name', models.CharField(max_length=128)),
                ('image', models.URLField(default='https://bitsofco.de/content/images/2018/12/broken-1.png', max_length=5000)),
                ('availability', models.CharField(default='Out of Stock', max_length=128)),
                ('category', models.CharField(default='General', max_length=128)),
                ('Retailer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.retailer')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
                ('user', models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_ht', models.FloatField(blank=True)),
                ('added_at', models.DateTimeField(default=datetime.datetime.now)),
                ('Status', models.CharField(default='Ordered', max_length=128)),
                ('Retailer_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.retailer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
                ('user', models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_ht', models.FloatField(blank=True)),
                ('added_at', models.DateTimeField(default=datetime.datetime.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
                ('user', models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
