# Generated by Django 3.2.7 on 2021-11-19 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.TextField()),
                ('gstNo', models.TextField(unique=True)),
                ('whyyou', models.TextField()),
                ('Products', models.TextField()),
                ('Retailer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('phone', models.CharField(default='None', max_length=128)),
                ('address', models.CharField(default='None', max_length=128)),
                ('city', models.CharField(default='None', max_length=128)),
                ('state', models.CharField(default='None', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.TextField()),
                ('gender', models.CharField(default='None', max_length=128)),
                ('hostel', models.CharField(default='None', max_length=128)),
                ('room', models.CharField(default='None', max_length=128)),
                ('phone', models.CharField(default='None', max_length=128)),
            ],
        ),
    ]
